package main

import "fmt"

type IceCreamMaker interface {
	Hello()
}

type Ben struct {
	id   int
	name string
}

func (b *Ben) Hello() {
	fmt.Printf("Ben says \"Hello my name is %s\"\n", b.name)
}

type Jerry struct {
	name string
}

func (j *Jerry) Hello() {
	fmt.Printf("Jerry says \"Hello my name is %s\"\n", j.name)
}

func main() {
	var ben = &Ben{
		id:   10,
		name: "ben",
	}

	var jerry = &Jerry{name: "jerry"}

	var maker IceCreamMaker = ben

	var loop0, loop1 func()

	loop0 = func() {
		maker = ben
		go loop1()
	}

	loop1 = func() {
		maker = jerry
		go loop0()
	}

	go loop0()

	for {
		maker.Hello()
	}
}

/**
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/zvan/go #gosetup
/usr/local/opt/go/libexec/bin/go build -o /private/var/folders/6w/c0xf6jjx6fz9_vlczm311f_40000gn/T/GoLand/___go_build_GeekGoCamp4_week3 /Users/zvan/go/src/GeekGoCamp4/week3/add.go #gosetup
/private/var/folders/6w/c0xf6jjx6fz9_vlczm311f_40000gn/T/GoLand/___go_build_GeekGoCamp4_week3
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"
Ben says "Hello my name is ben"
Ben says "Hello my name is ben"
Jerry says "Hello my name is jerry"

 */
